### PR TITLE
ionic/install_windows_src: More bulletproof terminal setup instructions

### PR DESCRIPTION
**Pull request by peci1**
# 🦟 Bug fix

## Summary
I've added a few tips for Windows usage based on my experience.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by peci1** [comment]
The PS console activation code comes from https://stackoverflow.com/questions/64149680/how-can-i-activate-a-conda-environment-from-powershell#comment122022285_67996662 .

**Comment by peci1** [comment]
I actually don't know if it's the intended behavior that Gazebo requires to be run inside a VS shell. However, that's what was needed on my system. Without it (and with conda activated and workspace sourced), I get:

```
λ gz sim -s
Library error for [D:/programming/gz9-ws/gz-ws/install/bin/gz-sim9-gz.dll]: can't load D:/programming/gz9-ws/gz-ws/install/bin/gz-sim9-gz.dll
```

**Comment by traversaro** [comment]
> I actually don't know if it's the intended behavior that Gazebo requires to be run inside a VS shell. However, that's what was needed on my system. Without it (and with conda activated and workspace sourced), I get:
> 
> ```
> λ gz sim -s
> Library error for [D:/programming/gz9-ws/gz-ws/install/bin/gz-sim9-gz.dll]: can't load D:/programming/gz9-ws/gz-ws/install/bin/gz-sim9-gz.dll
> ```

That is indeed strange. Are you using Command Prompt or Windows Powershell?

**Comment by peci1** [comment]
I'm using the command prompt.

**Comment by traversaro** [comment]
Then something is indeed strange. If you want to debug more, you could try to load `D:/programming/gz9-ws/gz-ws/install/bin/gz-sim9-gz.dll` in https://github.com/lucasg/Dependencies in the same environment you are trying to run, and check if some dependent .dll is missing.

**Comment by peci1** [comment]
Weird. I just rebooted the computer and now it works in a normal CMD shell.

One possibility is that I'm using "conemu" as the command prompt, which normally just spawns a CMD subprocess and works the same as CMD. However, I've noticed that conemu is unable to reload system env variables if you change them - it always needs to reboot the computer. I don't know exactly which system variable it needed, but my guess is that this requirement to reboot can be attributed to conemu and that it should not affect other users.

**Comment by peci1** [comment]
I've removed the wording about VS command prompt from this PR.

**Comment by azeey** [comment]
We've noticed that versions of tinyxml or Bullet installed via chocolatey (as used in the ROS 2 install instructions) might cause weird issues like this.

**Comment by peci1** [comment]
Oh, I haven't dived into any ROS 2 + GZ tutorials. Combining Conda + Choco packages, that must be a very "interesting"... hell :-D

**Review by azeey — APPROVED** [review]

**Comment by Apurborj** [comment]
Hi

**Pull request merged**
